server:
  port: 8080

# game configurations
game:
  pit-stones: 6

spring:
  #consul configurations
  #cloud:
  #  consul:
  #    host: localhost
  #    port: 8500
  #    discovery:
  #      prefer-ip-address: true
  #      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #mongodb configurations
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mankala_game_db
  #Sleuth configurations
  #sleuth:
  #  sampler:
  #    probability: 1

web:
  cors:
    allowed-origins: "http://localhost:4200"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"